slam_toolbox:
  ros__parameters:

    odom_frame: odom
    map_frame: map
    base_frame: base_frame
    scan_topic: /fused/laserscan

    mode: mapping

    resolution: 0.1
    transform_publish_period: 0.02
    map_update_interval: 3.0
