<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>muto_hexapod_lib_custom</name>
  <version>0.3.0</version>
  <description>ROS-packaged Muto hexapod serial control and commanded gait generation.</description>
  <maintainer email="nx-ros2@todo.todo">nx-ros2</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>python3-serial</exec_depend>

  <test_depend>ament_flake8</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
