# Natural-language description of the static object to actively search for.
string prompt
---
bool success
string message
muto_command_layer/ObjectMatch[] matches
---
uint8 PHASE_CHECKING_REGISTRY=1
uint8 PHASE_EXPLORING=2
uint8 PHASE_RECHECKING_REGISTRY=3
uint8 PHASE_STOPPING_EXPLORATION=4

uint8 phase
string status
uint32 confirmed_object_count
